version: "3.3"

services:
  postgres:
    container_name: backend-database
    image: postgres:14.1-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: backend
      POSTGRES_USER: ps_user
      POSTGRES_PASSWORD: ps_password
      POSTGRES_HOST: database
    ports:
      - "5432:5432"
